spring:
  datasource:
    url: ${JAWSDB_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5  # Adjust this according to your MySQL server's max_user_connections
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
server:
  port: ${PORT:8080}
