spring:
  application:
    name: job-app

# Default profile, typically used for local development
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 60000

jwt:
  secretKey: C8C6D159EB43729B1190D0EFE6907414677162741A2B067ECC985081D16BD577
  expiration: 86400000

server:
  port: ${PORT:8080}

place:
  url: https://maps.googleapis.com/maps/api/place
  apiKey: ${PLACE_API_KEY}
logging:
  level:
    root: INFO