server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=kyoka
#spring.mail.password=password

spring.mvc.cors.allowed-origins=http://localhost:3000
backend.base-url=http://localhost:8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kyoka.miyamura21@gmail.com
spring.mail.password=jqjzlwzfninaysxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true