server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://containers-us-west-61.railway.app:5967/railway
spring.datasource.username=postgres
spring.datasource.password=NSXxury1ZqnB8O70aT0A
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=kyoka
spring.mail.password=password

#help me!

#server.error.include-message=always
#server.error.include-binding-errors=always
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=kyoka
#spring.mail.password=password