name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: docker compose up
      run: docker compose up -d
    - name: Migrate DB
      run: ./gradlew flywayMigrate
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
        # Heroku CLIをセットアップ
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}     # Heroku API Key from GitHub Secrets
        heroku_app_name: "radiant-tor-04984"              # Your Heroku app name
        heroku_email: "kyoka.miyamura21@gmail.com"        # Your Heroku account email
        project_path: "./app/build/libs/*.jar"            # Path to the built JAR file