name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: docker compose up
      run: docker compose up -d
    - name: Migrate DB
      run: ./gradlew flywayMigrate
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test